
substitutions:
  device_name: "esp32-gree"
  device_description: "Control Gree FHBQ-D8-K via RS485"
  gree_tx_pin: GPIO19
  gree_rx_pin: GPIO18

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret ap_password

captive_portal:

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password
  platform: esphome

web_server:
  port: 80
  version: 3

switch:
  - platform: restart
    name: "${device_name} restart"

uart:
  id: mod_bus
  tx_pin: ${gree_tx_pin}
  rx_pin: ${gree_rx_pin}
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8

modbus:
  id: modbus_gree
  uart_id: mod_bus
  send_wait_time: 200ms

modbus_controller:
  - id: gree
    modbus_id: modbus_gree
    address: 0x2
    setup_priority: -10
    update_interval: 3s

select:
  - platform: modbus_controller
    modbus_controller_id: gree
    name: "Gree State"
    address: 4
    value_type: U_WORD
    icon: "mdi:power"
    optionsmap:
      "On": 0xAA
      "Off": 0x55
    use_write_multiple: true
  - platform: modbus_controller
    modbus_controller_id: gree
    name: "Gree Fan speed"
    address: 8
    value_type: U_WORD
    icon: "mdi:fan"
    optionsmap:
      "Low": 0
      "Medium": 1
      "High": 2
    use_write_multiple: true
  - platform: modbus_controller
    modbus_controller_id: gree
    name: "Gree Mode"
    address: 5
    value_type: U_WORD
    icon: "mdi:hvac"
    optionsmap:
      "Auto": 0
      "Bypass": 1
      "Heat Exchange": 2
    use_write_multiple: true
